on: [push]
name: Test
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: check out
        uses: actions/checkout@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test ./...

  build:
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: go build ./...

  run:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: exec
        run: ./main
