name: main
on:
  push:
    paths:
      - ".github/workflows/main.yml"
  schedule:
    - cron: "0 13 * * 1"

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: check out
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: version
        run: go version
      - name: build
        run: go build ./...
      - name: exec
        run: ./aws-services
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: update by .github/workflows/main.yml
