name: zenn
on:
  schedule:
    - cron: "* * * * 1"
  push:
    branches:
      - master

jobs:
  zenn:
    runs-on: ubuntu-20.04
    env:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    steps:
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: version
        run: go version
      - name: go get aws-services
        run: go get github.com/kis9a/aws-services
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: kis9a/kis9a
          path: kis9a
      - name: update zenn article
        run: |
          cd kis9a/
          git config user.name "kis9a"
          git config user.email "kis9ax@gmail.com"
          aws-services jp -t zenn/articles/aws-services.template -o zenn/articles/aws-services.md
          ls -la zenn/articles
          echo $REPO_TOKEN
          git add zenn/articles/aws-services.md
          git push https://kis9a:$REPO_TOKEN@github.com/kis9a/kis9a.git
